#' Compute channel flow parameters and geometry for sensitivity analysis
#'
#' @param channel_df A `data.frame` or `tibble` generated by `by_*_df` functions
#' (e.g., `by_width_df`). It must include columns such as `total_discharge`,
#' `width`, `slope`, `particle_size`, `side_slope`, and `gravity`.
#'
#' @return A `tibble` with additional columns for computed flow parameters and
#' channel geometry (e.g., `unit_discharge`, `critical_depth`, `froude`).
#'
#' @importFrom dplyr mutate
#' @export
compute_channel_dimensions <- function(channel_df) {
  # Constants
  h2o_specific_weight <- 9787            # N/m^3
  ft_per_m <- 3.2808
  wd <- unique(channel_df$water_density) # user-provided water density (kg/m^3)

  channel_df %>%
    mutate(
      # Channel Flow Parameters
      unit_discharge = total_discharge / width,
      critical_depth = (unit_discharge^2 / gravity)^(1 / 3),
      critical_velocity = unit_discharge / critical_depth,
      mannings_n = 0.034 * (particle_size * ft_per_m)^(1 / 6),
      normal_depth = ((unit_discharge * mannings_n) / sqrt(slope))^(3 / 5),
      normal_velocity = unit_discharge / normal_depth,
      froude = normal_velocity / sqrt(gravity * normal_depth),
      shear_stress = h2o_specific_weight * normal_velocity * slope,
      avail_stream_power = (h2o_specific_weight * unit_discharge * slope) / 1000,
      applied_stream_power = (7.853 * wd * (shear_stress / wd)^(3 / 2)) / 1000,

      # Channel Geometry
      side_angle = atan(1 / side_slope) * (180 / pi),
      depth = normal_depth * 2,
      length_side_horz = depth * side_slope,
      length_left_bank = length_side_horz / cos(side_angle * (pi / 180))
    )
}