#' Compute stone size and derived metrics using precomputed channel dimensions
#'
#' @param channel_dimensions A `data.frame` or `tibble` generated by
#' `compute_channel_dimensions`. It must include flow parameters such as
#' `unit_discharge`, `normal_velocity`, and `slope`, as well as channel
#' geometry parameters.
#'
#' @return A `tibble` in long-format with stone size metrics (e.g.,
#' `stone_diameter`, `stone_volume`) calculated for each method.
#'
#' @importFrom dplyr mutate rowwise
#' @importFrom tidyr unnest
#' @importFrom purrr map_dfr
#' @export
compute_stone_metrics <- function(channel_dimensions) {
  stone_methods <- c("nrcs", "usace", "abt_johnson", "isbash", "usbr")
  
  channel_dimensions %>%
    dplyr::rowwise() %>%
    dplyr::mutate(
      stone_metrics = list(purrr::map_dfr(
        stone_methods,
        ~ {
          # Calculate stone diameter
          stone_diameter <- compute_stone_size(
            method = .x,
            unit_discharge = unit_discharge,
            slope = slope,
            normal_velocity = normal_velocity,
            stone_specific_weight = stone_density * gravity,
            h2o_specific_weight = 9787,  # Water specific weight
            g = gravity
          )
          
          # Derived metrics
          tibble::tibble(
            method = .x,
            stone_diameter = stone_diameter,
            stone_weight_kg = (stone_diameter^3 * pi * (stone_density * gravity)) / (6 * gravity),
            mattress_thickness = 2 * stone_diameter,
            stone_vol_m3 = contingency * (
              mattress_thickness * (width + depth) * length
            ) * (1 - porosity)
          )
        }
      ))
    ) %>%
    tidyr::unnest(stone_metrics)
}