#' @title Plot Stone Size by Methods
#' @description Plot estimated stone size according to several different
#'              methods.
#' @param stone_metrics data frame; A long-format data frame generated by 
#'                      `compute_stone_metrics`. Must include `method` 
#'                      and `stone_diameter` columns.
#' @param x_axis       character; The variable to use for the x-axis. One of
#'                     "width", "length", "slope", "particle_size"
#' @returns a ggplot2 object
#' @export
#' @importFrom tidyr pivot_longer starts_with
#' @importFrom stringr str_remove str_to_upper
#' @importFrom dplyr mutate
#' @importFrom ggplot2 ggplot aes geom_line scale_color_brewer labs
#'             theme_light
#' @importFrom paletteer scale_color_paletteer_d
#' @importFrom NatParksPalettes NatParksPalettes
plot_stone_size_method <- function(stone_metrics, x_axis) {
  # Validate x_axis
  valid_x_axes <- c("width", "length", "slope", "particle_size")
  if (!(x_axis %in% valid_x_axes)) {
    stop("x_axis must be one of: ", paste(valid_x_axes, collapse = ", "))
  }

  # Validate required columns
  required_cols <- c("method", "stone_diameter", x_axis)
  missing_cols <- setdiff(required_cols, colnames(stone_metrics))
  if (length(missing_cols) > 0) {
    stop("The following required columns are missing in the input data: ", 
         paste(missing_cols, collapse = ", "))
  }

  # Define x_axis labels
  x_axis_label <- switch(x_axis,
                         width         = "Width (m)",
                         length        = "Length (m)",
                         slope         = "Slope",
                         particle_size = "Particle Size (m)")

  # Create plot
  stone_plot <- ggplot(stone_metrics,
                       aes(x = .data[[x_axis]],
                           y = stone_diameter,
                           color = method)) +
    geom_line(linewidth = 2.5) +
    scale_color_paletteer_d("NatParksPalettes::KingsCanyon") +
    labs(title = "Stone Size by Methods",
         x = x_axis_label, y = "Stone Size (m)") +
    theme_light()

  return(stone_plot)
}
